name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_16:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests --enable-code-coverage
      - name: Test
        run: swift test --skip-build --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/IdentifiableContinuationPackageTests.xctest/Contents/MacOS/IdentifiableContinuationPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage_report.lcov

  xcode_15_4:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_10:
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_6_0:
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_6_0_musl:
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Install SDK
        run: swift sdk install https://download.swift.org/swift-6.0.3-release/static-sdk/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 67f765e0030e661a7450f7e4877cfe008db4f57f177d5a08a6e26fd661cdd0bd
      - name: Build
        run: swift build --swift-sdk x86_64-swift-linux-musl
